FROM ubuntu:20.04

ARG AzureCliVersion=2.44.1-1~bionic
ARG AzurePowershellVersion=4.5.0
ARG DotnetSdkVersion=6.0
ARG HelmVersion=v3.7.1
ARG KubectlVersion=1.18.8-00
ARG KubeloginVersion=v0.0.25
ARG OctopusCliVersion=9.1.7
ARG OctopusClientVersion=11.6.3644
ARG PowershellVersion=7.2.7-1.deb
ARG NodejsVersion=10

# get `wget` & software-properties-common
# https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7#ubuntu-1804
RUN apt-get update -qq && \
    apt-get install -qq -y wget unzip apt-utils curl software-properties-common iputils-ping

# get powershell for 22.04
RUN wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update -qq && \
    add-apt-repository universe && \
    apt-get install -qq -y powershell=${PowershellVersion}

# Get Octo CLI
# https://octopus.com/downloads/octopuscli#linux
RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends gnupg curl ca-certificates apt-transport-https && \
    curl -sSfL https://apt.octopus.com/public.key | apt-key add - && \
    sh -c "echo deb https://apt.octopus.com/ stable main > /etc/apt/sources.list.d/octopus.com.list" && \
    apt-get update -qq && \
    apt-get install -qq -y octopuscli=${OctopusCliVersion}

# Install Octopus Client
# https://octopus.com/docs/octopus-rest-api/octopus.client
RUN pwsh -c 'Install-Package -Force Octopus.Client -MaximumVersion "'${OctopusClientVersion}'" -source https://www.nuget.org/api/v2 -SkipDependencies' && \
    octopusClientPackagePath=$(pwsh -c '(Get-Item ((Get-Package Octopus.Client).source)).Directory.FullName') && \
    cp -r $octopusClientPackagePath/lib/netstandard2.0/* .

# Get AZ Powershell core modules
# https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-3.6.1
RUN pwsh -c 'Install-Module -Force -Name Az -AllowClobber -Scope AllUsers -MaximumVersion "'${AzurePowershellVersion}'"'

# Get Helm3
RUN wget --quiet -O - https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash -s -- -v ${HelmVersion}

# Get .NET SDK 6.0
# https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804
# https://learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup
RUN DOTNET_CLI_TELEMETRY_OPTOUT=1 && \
    touch /etc/apt/preferences && \
    echo "Package: dotnet* aspnet* netstandard* \nPin: origin \"packages.microsoft.com\" \nPin-Priority: -10" > /etc/apt/preferences && \
    echo "export DOTNET_CLI_TELEMETRY_OPTOUT=1" > /etc/profile.d/set-dotnet-env-vars.sh && \
    apt-get install -qq -y apt-transport-https && \
    apt-get update -qq && \
    apt-get install -qq -y dotnet-sdk-${DotnetSdkVersion}

# Get Libssl 1.1, required for Azure CLI as of Ubuntu 22.04. This can be removed when a proper Azure CLI ubuntu 22.04 version is avaliable
RUN wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb && \
    dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb && \
    rm -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

# Get Azure CLI
# https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest
RUN wget --quiet -O - https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null && \
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main" | tee /etc/apt/sources.list.d/azure-cli.list && \
    apt-get update -qq && \
    apt-get install -qq -y azure-cli=${AzureCliVersion}

# Install Bicep using Azure CLI
# https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#azure-cli
RUN az bicep install

# Get NodeJS
# https://websiteforstudents.com/how-to-install-node-js-10-11-12-on-ubuntu-16-04-18-04-via-apt-and-snap/\
RUN wget --quiet -O - https://deb.nodesource.com/setup_${NodejsVersion}.x | bash && \
    apt-get install -qq -y nodejs

# Get Kubectl
# https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-using-native-package-management
RUN wget --quiet -O - https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -  && \
    echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list && \
    apt-get update -qq && apt-get install -qq -y kubectl=${KubectlVersion}

# Get Kubelogin
RUN wget --quiet https://github.com/Azure/kubelogin/releases/download/${KubeloginVersion}/kubelogin-linux-amd64.zip && \
    unzip kubelogin-linux-amd64.zip -d kubelogin-linux-amd64 && \
    mv kubelogin-linux-amd64/bin/linux_amd64/kubelogin /usr/local/bin && \
    rm -rf kubelogin-linux-amd64 && \
    rm kubelogin-linux-amd64.zip
