# escape=`

FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
SHELL ["powershell", "-Command"]

ARG KubeloginVersion=0.0.30
ARG NodeJSVersion=18.17.0
ARG OctopusCliVersion=9.1.7
ARG OctopusClientVersion=14.3.722
ARG PowershellVersion=7.2.13
ARG ScriptCSVersion=0.17.1
ARG 7ZipVersion=23.1.0

# Choco
RUN $ProgressPreference = 'SilentlyContinue'; `
    Set-ExecutionPolicy Bypass -Scope Process -Force; `
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

# Powershell Core
RUN choco install powershell-core --yes --version $Env:PowershellVersion --no-progress

# Disable colors in PowerShell
RUN pwsh -c 'mkdir -p "$(dirname "$profile")" && touch "$profile" && echo '$PSStyle.OutputRendering = "PlainText"' >> $profile && . $profile'

SHELL ["pwsh", "-Command"]

# dotnet 6.0+
RUN Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -outFile 'dotnet-install.ps1'; `
    [Environment]::SetEnvironmentVariable('DOTNET_CLI_TELEMETRY_OPTOUT', '1', 'Machine'); `
    .\dotnet-install.ps1 -Channel '6.0'; `
    rm dotnet-install.ps1

# Azure CLI
RUN choco install azure-cli -y --no-progress
RUN az upgrade

# Bicep using Azure CLI
# https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#azure-cli
RUN az bicep install
RUN az bicep upgrade

# Azure PowerShell modules
# https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-3.6.1
RUN Install-Module -Force -Name Az -AllowClobber -Scope AllUsers; `
    Enable-AzureRmAlias -Scope LocalMachine

# NodeJS
RUN choco install nodejs-lts -y --version $Env:NodeJSVersion --no-progress

# kubectl
RUN choco install kubernetes-cli -y --no-progress

# kubelogin
RUN choco install azure-kubelogin --version $Env:KubeloginVersion --no-progress -y

# helm 3
RUN choco install -y kubernetes-helm --no-progress

# 7zip
RUN choco install 7zip -y --version $Env:7ZipVersion --no-progress

# ScriptCS
RUN choco install scriptcs -y --version $Env:ScriptCSVersion --no-progress

# Octopus Tools
RUN choco install octopustools -y --version $Env:OctopusCliVersion --no-progress

# Octopus Client
RUN Install-Package Octopus.Client -source https://www.nuget.org/api/v2 -SkipDependencies -Force -RequiredVersion $Env:OctopusClientVersion

# Update path for new tools
COPY .\windows-ltsc2019-node18\scripts\update_path.cmd C:\update_path.cmd
RUN C:\update_path.cmd;
