name: push-docker-images

on:
  push:
    branches: "*"

env:
  SUBSCRIPTON_CREDENTIALS: ${{ secrets.AZURE_AQOVIA_CI_RG_CREDENTIALS }}
  CONTAINER_REGISTRY_NAME: aqovia
  CONTAINER_REPOSITORY: octopus-workers
  IMAGE_TAG: '1.0'

jobs:
  build-and-push:
    strategy:
      matrix:
        name: ["ubuntu-22.04", "windows-ltsc2019"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ env.SUBSCRIPTON_CREDENTIALS }}
      - uses: azure/CLI@v1
        name: Azure CLI script
        with:
          inlineScript: |
            name='${{ matrix.name }}'
            platform='linux'
            if [[ "$name" == *"windows"* ]]; then
              platform='windows'
            fi
            az acr login --name ${{ env.CONTAINER_REGISTRY_NAME }} --expose-token
            az acr build \
              --registry ${{ env.CONTAINER_REGISTRY_NAME }} \
              . \
              --file '${{ matrix.name }}/dockerfile' \
              --image '${{ env.CONTAINER_REPOSITORY }}:${{ env.IMAGE_TAG }}-${{ matrix.name }}' \
              --platform $platform
